baseURL = "https://azmisblog.netlify.app/"
languageCode = "en-us"
title = "Azmi's Blog"
theme = "PaperMod"
enableRobotsTXT = true

[pagination]
  pagerSize = 5

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  defaultTheme = "auto"
  # Add these lines:
  ShowFullTextinRSS = true
  ShowShareButtons = true
  ShowToc = false
  disableSpecial1stPost = false
  displayFullLangName = true
  
  # Homepage settings
  homeInfoParams.Title = "Welcome to Azmi's Blog"
  homeInfoParams.Content = "My personal blog about tech, development, and more."

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1